### ISSUE TITLE
Bulky Repo

### ISSUE THREAD

**Issue by gavindsouza** [earthians/marley#1]
This repository contains all of ERPNext's histories, and everything apart from the healthcare module was deleted in one commit. 

I feel we should instead only keep history (or commits) pertaining to the healthcare module. This would bring down the size of the repo considerably for starters. That alone will reduce the overhead to develop and maintain this app. Debugging across histories will be easier since we won't be dealing with so much baggage (909MiB at this point alone) 😅.

cc: @ChillarAnand

**Comment by ChillarAnand** [comment]
| History  | Commits | Size |
| ------------- | ------------- | --- |
| No rewrite  |  38k | ~1.7G| |
| Non-healthcare rewrite | 10K | ~0.3G |
| Complete rewrite | 7k | ~30M |
| Fresh repo | - | ~3M |

Since we moved healthcare as a separate app, the directory structure has changed. Due to this, while completely re-writing the history, git is pruning commits related to healthcare also. This might cause issues in future when we have to run git blame/bisect etc.

If we re-write history for all modules excluding healthcare, then repo size is coming to ~300MB.

cc: @ankush, @hasnain2808

**Comment by ankush** [comment]
I think just by getting rid of translation and docs you'll save a HUGE amount of space.

Check this: (large objects in ERPNext repo history):  https://gist.github.com/ankush/ac3c49401ee240ea43780acf41fcbf00


90%+ of files >100 KB are just translations or doc images!

**Comment by ankush** [comment]
have you tried this: https://github.com/rtyley/bfg-repo-cleaner ?

**Comment by ChillarAnand** [comment]
Thanks, @ankush. Except yarn.lock file, all other files >100KB are not required. 

Ran `$ bfg --strip-blobs-bigger-than 100K` and the repo size is down to ~140MB.

**Comment by gavindsouza** [comment]
> Since we moved healthcare as a separate app, the directory structure has changed. Due to this, while completely re-writing the history, git is pruning commits related to healthcare also. This might cause issues in future when we have to run git blame/bisect etc.

could we get rid of everything except healthcare from ERPNext and then change the paths, and cherry-pick all later commits after, or is it too late/pointless for that now?

**Comment by ChillarAnand** [comment]
@gavindsouza cherry picking the later commits will take additional time. Since some additional healthcare prs are merged & code cleanup is done in erpnext, it makes sense to cherry pick the later commits and apply them. 

With the above approach, repo size is reduced to ~5MB & history is preserved without any mangling. 

Build is passing now & basic testing is done. Need to do one more round of testing to make sure nothing is broken.

**Comment by gavindsouza** [comment]
Just cloned the repo again, inital clone size has come down to `3.3MiB` 😄

**Comment by ChillarAnand** [comment]
Closing this as the repo size has reduced considerably. 

@ruchamahabal, @gavindsouza, @ankush Thanks for the help.
