### ISSUE TITLE
Page sample-collection not found

### ISSUE THREAD

**Issue by imbraintl** [earthians/marley#338]
### Information about bug

![image](https://github.com/frappe/health/assets/105174874/90c140ec-6af2-44f7-980d-4304c1926176)

### Module

Laboratory

### Version

Frappe Health Version - Develop

### Installation method

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vamagithub** [comment]
Can you please elaborate on steps to re-produce this bug? @imbraintl

**Comment by edtimer** [comment]
Got the same error, happens when creating a slaes invoice that contains a lab test. Disabling the dependency on sample collection by navigating to Healthcare > Configurations > Lab Test Settings solved the issue; however is a temprary solution. you can refer to [issue](https://github.com/earthians/marley/pull/228)

**Comment by imbraintl** [comment]
fixed here #228
